In [83]:
import os, sys, time, resource, re, gc, shutil
from multiprocess import Pool
from functools import partial
from tabulate import tabulate
from urllib.parse import urlparse, parse_qsl

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mongoengine.queryset.visitor import Q
import django
from django.db.models import Count, Sum
sys.path.append('/home/galm/software/tmv/BasicBrowser/')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "BasicBrowser.settings")
django.setup()

from django.forms.models import model_to_dict

from scoping.models import *
from tmv_app.models import *

In [13]:
run_id = 96
qid = 1053

In [77]:
docs = Doc.objects.filter(query=qid)
wcs = WC.objects.all()[:5]
topics = Topic.objects.filter(run_id_id=run_id)[:5]

In [78]:
for wc in wcs.iterator():
    print(wc.text)

Oceanography
Ecology
Chemistry, Multidisciplinary
Biodiversity Conservation
Biology

In [90]:
tvalues = []
for t in topics:
    tv = {"t_id": t.pk, "title":t.title, "score": t.score}
    for wc in wcs.iterator():
        dts = DocTopic.objects.filter(
            run_id=run_id,topic=t,doc__wc=wc
        ).aggregate(
            total = Sum('score')
        )
       

        twcv = {
            "wc_id" : wc.id,
            "oecd" : wc.oecd,
            "oecd_fos_text" : wc.oecd_fos_text,
            "wc_score" : dts['total']
        }
        twcv.update(tv)
        #twcv['text'] = wc.text
        #twcv['oecd'] = wc.oecd
        #twcv['oecd_fos_text'] = wc.oecd_fos_text
        #twcv['score'] = dts['total']
        #print(wc.__dict__)
        #print(twcv)    
        #print(t.title)
        #print(wc.text)
        
        tvalues.append(twcv)

In [91]:
df = pd.DataFrame.from_dict(list(tvalues))
df.head(221)

         score   t_id                       title  wc_id
0   120.501380  10412     {polici, develop, plan}      1
1   120.501380  10412     {polici, develop, plan}    236
2   120.501380  10412     {polici, develop, plan}    237
3   120.501380  10412     {polici, develop, plan}    238
4   120.501380  10412     {polici, develop, plan}    239
5    60.906291  10413  {energi, consumpt, effici}      1
6    60.906291  10413  {energi, consumpt, effici}    236
7    60.906291  10413  {energi, consumpt, effici}    237
8    60.906291  10413  {energi, consumpt, effici}    238
9    60.906291  10413  {energi, consumpt, effici}    239
10   54.146647  10414        {wast, manag, solid}      1
11   54.146647  10414        {wast, manag, solid}    236
12   54.146647  10414        {wast, manag, solid}    237
13   54.146647  10414        {wast, manag, solid}    238
14   54.146647  10414        {wast, manag, solid}    239
15   45.800625  10415      {price, congest, road}      1
16   45.800625  10415      {price, congest, road}    236
17   45.800625  10415      {price, congest, road}    237
18   45.800625  10415      {price, congest, road}    238
19   45.800625  10415      {price, congest, road}    239
20   30.031965  10416        {park, space, price}      1
21   30.031965  10416        {park, space, price}    236
22   30.031965  10416        {park, space, price}    237
23   30.031965  10416        {park, space, price}    238
24   30.031965  10416        {park, space, price}    239

In [89]:
len(df)

25

In [62]:
df

,id,oecd,oecd_fos_text,score,text,title,wc_id
0,10412,Natural Sciences,Biological sciences,120.501380,Biology,"{polici, develop, plan}",239
1,10412,Natural Sciences,Biological sciences,120.501380,Biology,"{polici, develop, plan}",239
2,10412,Natural Sciences,Biological sciences,120.501380,Biology,"{polici, develop, plan}",239
3,10412,Natural Sciences,Biological sciences,120.501380,Biology,"{polici, develop, plan}",239
4,10412,Natural Sciences,Biological sciences,120.501380,Biology,"{polici, develop, plan}",239
5,10413,Natural Sciences,Biological sciences,60.906291,Biology,"{energi, consumpt, effici}",239
6,10413,Natural Sciences,Biological sciences,60.906291,Biology,"{energi, consumpt, effici}",239
7,10413,Natural Sciences,Biological sciences,60.906291,Biology,"{energi, consumpt, effici}",239
8,10413,Natural Sciences,Biological sciences,60.906291,Biology,"{energi, consumpt, effici}",239
9,10413,Natural Sciences,Biological sciences,60.906291,Biology,"{energi, consumpt, effici}",239
10,10414,Natural Sciences,Biological sciences,54.146647,Biology,"{wast, manag, solid}",239
11,10414,Natural Sciences,Biological sciences,54.146647,Biology,"{wast, manag, solid}",239
12,10414,Natural Sciences,Biological sciences,54.146647,Biology,"{wast, manag, solid}",239
13,10414,Natural Sciences,Biological sciences,54.146647,Biology,"{wast, manag, solid}",239
14,10414,Natural Sciences,Biological sciences,54.146647,Biology,"{wast, manag, solid}",239
15,10415,Natural Sciences,Biological sciences,45.800625,Biology,"{price, congest, road}",239
16,10415,Natural Sciences,Biological sciences,45.800625,Biology,"{price, congest, road}",239
17,10415,Natural Sciences,Biological sciences,45.800625,Biology,"{price, congest, road}",239
18,10415,Natural Sciences,Biological sciences,45.800625,Biology,"{price, congest, road}",239
19,10415,Natural Sciences,Biological sciences,45.800625,Biology,"{price, congest, road}",239
20,10416,Natural Sciences,Biological sciences,30.031965,Biology,"{park, space, price}",239
21,10416,Natural Sciences,Biological sciences,30.031965,Biology,"{park, space, price}",239
22,10416,Natural Sciences,Biological sciences,30.031965,Biology,"{park, space, price}",239
23,10416,Natural Sciences,Biological sciences,30.031965,Biology,"{park, space, price}",239
24,10416,Natural Sciences,Biological sciences,30.031965,Biology,"{park, space, price}",239
25,10417,Natural Sciences,Biological sciences,74.656626,Biology,"{model, network, optim}",239
26,10417,Natural Sciences,Biological sciences,74.656626,Biology,"{model, network, optim}",239
27,10417,Natural Sciences,Biological sciences,74.656626,Biology,"{model, network, optim}",239
28,10417,Natural Sciences,Biological sciences,74.656626,Biology,"{model, network, optim}",239
29,10417,Natural Sciences,Biological sciences,74.656626,Biology,"{model, network, optim}",239
...,...,...,...,...,...,...,...
80,10428,Natural Sciences,Biological sciences,52.281514,Biology,"{urban, land, citi}",239
81,10428,Natural Sciences,Biological sciences,52.281514,Biology,"{urban, land, citi}",239
82,10428,Natural Sciences,Biological sciences,52.281514,Biology,"{urban, land, citi}",239
83,10428,Natural Sciences,Biological sciences,52.281514,Biology,"{urban, land, citi}",239
84,10428,Natural Sciences,Biological sciences,52.281514,Biology,"{urban, land, citi}",239
85,10429,Natural Sciences,Biological sciences,23.771116,Biology,"{toll, lane, link}",239
86,10429,Natural Sciences,Biological sciences,23.771116,Biology,"{toll, lane, link}",239
87,10429,Natural Sciences,Biological sciences,23.771116,Biology,"{toll, lane, link}",239
88,10429,Natural Sciences,Biological sciences,23.771116,Biology,"{toll, lane, link}",239
89,10429,Natural Sciences,Biological sciences,23.771116,Biology,"{toll, lane, link}",239
90,10430,Natural Sciences,Biological sciences,33.418094,Biology,"{treatment, water, wastewat}",239
91,10430,Natural Sciences,Biological sciences,33.418094,Biology,"{treatment, water, wastewat}",239
92,10430,Natural Sciences,Biological sciences,33.418094,Biology,"{treatment, water, wastewat}",239
93,10430,Natural Sciences,Biological sciences,33.418094,Biology,"{treatment, water, wastewat}",239
94,10430,Natural Sciences,Biological sciences,33.418094,Biology,"{treatment, water, wastewat}",239
95,10431,Natural Sciences,Biological sciences,53.844469,Biology,"{travel, mode, choic}",239
96,10431,Natural Sciences,Biological sciences,53.844469,Biology,"{travel, mode, choic}",239
97,10431,Natural Sciences,Biological sciences,53.844469,Biology,"{travel, mode, choic}",239
98,10431,Natural Sciences,Biological sciences,53.844469,Biology,"{travel, mode, choic}",239
99,10431,Natural Sciences,Biological sciences,53.844469,Biology,"{travel, mode, choic}",239
100,10432,Natural Sciences,Biological sciences,21.714217,Biology,"{hous, passiv, construct}",239
101,10432,Natural Sciences,Biological sciences,21.714217,Biology,"{hous, passiv, construct}",239
102,10432,Natural Sciences,Biological sciences,21.714217,Biology,"{hous, passiv, construct}",239
103,10432,Natural Sciences,Biological sciences,21.714217,Biology,"{hous, passiv, construct}",239
104,10432,Natural Sciences,Biological sciences,21.714217,Biology,"{hous, passiv, construct}",239
105,10433,Natural Sciences,Biological sciences,20.787708,Biology,"{bicycl, cycl, cyclist}",239
106,10433,Natural Sciences,Biological sciences,20.787708,Biology,"{bicycl, cycl, cyclist}",239
107,10433,Natural Sciences,Biological sciences,20.787708,Biology,"{bicycl, cycl, cyclist}",239
108,10433,Natural Sciences,Biological sciences,20.787708,Biology,"{bicycl, cycl, cyclist}",239
109,10433,Natural Sciences,Biological sciences,20.787708,Biology,"{bicycl, cycl, cyclist}",239

In [74]:
for tv in tvalues[0:10]:
    print(tv)

{'wc_id': 239, 'score': 120.501380015479, 't_id': 10412, 'title': '{polici, develop, plan}'}
{'wc_id': 239, 'score': 120.501380015479, 't_id': 10412, 'title': '{polici, develop, plan}'}
{'wc_id': 239, 'score': 120.501380015479, 't_id': 10412, 'title': '{polici, develop, plan}'}
{'wc_id': 239, 'score': 120.501380015479, 't_id': 10412, 'title': '{polici, develop, plan}'}
{'wc_id': 239, 'score': 120.501380015479, 't_id': 10412, 'title': '{polici, develop, plan}'}
{'wc_id': 239, 'score': 60.9062907068572, 't_id': 10413, 'title': '{energi, consumpt, effici}'}
{'wc_id': 239, 'score': 60.9062907068572, 't_id': 10413, 'title': '{energi, consumpt, effici}'}
{'wc_id': 239, 'score': 60.9062907068572, 't_id': 10413, 'title': '{energi, consumpt, effici}'}
{'wc_id': 239, 'score': 60.9062907068572, 't_id': 10413, 'title': '{energi, consumpt, effici}'}
{'wc_id': 239, 'score': 60.9062907068572, 't_id': 10413, 'title': '{energi, consumpt, effici}'}